import styles from './ChatModal.module.css'
import { motion } from 'framer-motion'
import { useActions } from '../../hooks/useActions'
import TokensCounter from '../OpenAiChat/TokensCounter'
import { CgCloseR } from 'react-icons/cg'
import { staggerContainer, zoomIn } from '../../utils/motion'

const ChatModal = () => {
  const { closeChatModal } = useActions()
  const handleModal = () => {
    closeChatModal()
  }

  return (
    <aside className={styles.chat_modal}>
      <CgCloseR className={styles.icon} onClick={handleModal} />
      <div className={styles.modal_container}>
        {/* <div className={styles.modal_content}>
          <p>
            Prompt tokens are the text or prompt provided by the user to instruct the language model for generating a
            response. These tokens act as the initial input for the model. Completion tokens are generated by the
            language model as the output or response based on the provided prompt.
          </p>
          <p>
            These tokens form the complete text generated by the model. The price for total tokens count is $0.002 per
            1000 tokens. This means that for every 1000 tokens generated by the model, there is a cost of $0.002. The
            total tokens count includes both the prompt tokens and the completion tokens.
          </p>
          <p>
            In summary, prompt tokens are the input instructions provided by the user, completion tokens are the
            generated output by the model, and the price for total tokens count is the cost associated with generating
            the complete text based on the prompt.
          </p>
        </div> */}
        <TokensCounter />
      </div>
    </aside>
  )
}
export default ChatModal
